---
packs:
  # Using a pack found within the config repo in /packs/wordpress
  - pack: wordpress
    # Values can be included here
    values:
      mysql:
        image:
          repository: mysql # format: registry.custom.com/me/my_image || me/my_image || myimage
          tag: "5.7"
          tag_pattern: "semver:>=5.7.10" # image: {tag_pattern: ...} will be used by swarm-sync to find the newest matching tag from registry
        root_password: changemeroot
      wordpress:
        image:
          repository: wordpress
          tag: latest
      user: wp
      password: changeme
      database: wordpress

    # Using a pack from the official "incubator" repo
  - pack: official/incubator/swarm-sync
    # Alternative to values, we can load values from a file in stacks/[stack]/values/ using values_file
    values_file: swarm-sync-values.yml

  - pack: official/incubator/portainer
    # Accept all the defaults from the pack, override no values
